### PR TITLE
auto line break long candidate URLs

### PR DESCRIPTION
**Pull request by ckingbailey**
tbh, this is an awkward solution, but the only other solution I could think of was to hide or scroll the overflow, which is not any less awkward

### CODE REVIEW

**Comment by ckingbailey** [comment]
screen shot 2018-09-09 at 9 35 04 pm
This is what it looks like in the best case. Line breaks on a dot .

**Comment by ckingbailey** [comment]
screen shot 2018-09-09 at 9 36 15 pm
This is what it looks like in a less ideal case. Line breaks on a word

**Comment by ckingbailey** [comment]
#205

**Comment by adborden** [comment]
Yeah, this is a great solution for now. I think we want to re-work the candidate summary on small screens in the future. Some thoughts:

- Maybe the photo should just stack, that way you have the full width for things like text and links.
- An alternative to wrapping would be to use text-overflow ellipsis.
- Probably want to "prettify" up the link so it doesn't include `https://www.` in the display.
- If we want to keep the wrapping, add padding so the 2nd line is aligned with the text of the first line instead of under the icon.

**Comment by adborden** [comment]
I'll get this merged.

**Pull request merged**
