### PR TITLE
Re-add referendums to ballot nav

### LINKED ISSUE #162: Restore referendums on ballot nav
We removed the referendums from the ballot navigation sidebar. When the data is QA'd, we can restore the referendums.

- [ ] depends on #161

### PR DESCRIPTION
**Pull request by adborden**
Resolves #162 

- [x] This is blocked by #161 

Desktop
screencapture-localhost-4000-office-oakland-2018-11-06-mayor-2018-09-06-13_26_12

---

Mobile

screencapture-localhost-4000-office-oakland-2018-11-06-mayor-2018-09-06-13_26_58

### CODE REVIEW

**Comment by adborden** [comment]
@tdooner i'll look at the tests, but this is the PR to merge once ballot measures are :a: :ok:

**Comment by ckingbailey** [comment]
screen shot 2018-09-09 at 9 49 11 pm
The way the horizontal lines line up here feels funny. It makes the spacing at the top look "off" between the left and right sides. Perhaps this is an issue for @elinaru and a separate PR tho.

**Comment by ckingbailey** [comment]
screen shot 2018-09-09 at 9 50 14 pm
For reference, here's how it looks before ballots get put back in there

**Comment by adborden** [comment]
@ckingbailey good point with the border. We've gone back and forth with that in the past because it's tricky to get it to line up properly. I'll remove it for now.

**Pull request merged**
