### PR TITLE
Interactive contributions table on committee page

### LINKED ISSUE #155: Contributor filter on committee page
Impement a text box that performs a filter on the contributions table based on the contributor name. This should work similar to the [contributor filter from the 2016 site](http://www.opendisclosure.io/#!/committee/1388168).

Part of https://github.com/caciviclab/odca-jekyll/issues/149

### PR DESCRIPTION
**Pull request by adborden**
Fixes #155 #156 

For parity with the [2016 site](https://www.opendisclosure.io/#!/), this adds the contributor filter and sortable columns to the contributions table.

- [x] Styling
- [x] Accessibility check
- [x] Improve how JS components are activated (maybe with web components shim?)

### CODE REVIEW

**Comment by adborden** [comment]
@anlawyer here's the branch. I ended up just moving the entire component to React, Jekyll doesn't render it anymore. This makes more sense to me than trying to maintain the component in two technologies. We sill want to figure out a cleaner way to activate these React UI components.

Do you want to help me with this? Either on the styling or on the activation part.

**Comment by anlawyer** [comment]
Definitely, would love to help! Let me know which would help you the most. Code looks awesome so far.

**Comment by adborden** [comment]
@anlawyer if you do any work on this, would you mind creating a new branch based on this one? and then we'll create PRs with this branch as the base.

**Comment by anlawyer** [comment]
Will do - thanks for the headsup!

**Comment by anlawyer** [comment]
I noticed that on the contributions page where we're doing the sorting/filter, there isn't a way to return to the previous page. The best option currently without hitting the browser's back button is to click the brand logo in the navbar which takes you back to the landing page. In the 2016 site, there's a breadcrumb nav - and looks like we want something similar here per Elina's mock-ups.

Would this fall under the styling aspect for this task, or is it more of a global site issue?

**Comment by anlawyer** [comment]
Not as well as I had hoped :/ @ckingbailey offered to help out, I'll touch base with him and see what we can hammer out.

**Comment by ckingbailey** [comment]
Yeah @anlawyer let's divide and conquer! ✊⚔️💻

**Comment by adborden** [comment]
@anlawyer I re-added the `outline` property so that keyboard navigation has a visual indicator.

**Comment by sfdoran** [comment]
Yay!

**Pull request merged**
