### PR TITLE
Add candidate pics

### PR DESCRIPTION
**Pull request by elinaru**
Adding: Kyra-Mungia.jpeg
Renia-Webb-sm.png
Yakpasua Zazaboi.jpg

This work resolves #<issue-number>.

Please include a description of the work.

### Previews

Large screens

Small screens

### CODE REVIEW

**Comment by ckingbailey** [comment]
Could be helpful to the developer to standardize these names. I realize we've never done that before, but that doesn't mean we can't do so going forward! I suggest no caps, hyphens, no suffixes like "sm", but am open to other ideas.

**Comment by elinaru** [comment]
I will try to bear that in mind for the next round of photos.

**Comment by ckingbailey** [comment]
Is it too much of a pain to change the names this time? Mind if I do?

**Comment by elinaru** [comment]
Hey @ckingbailey  - Sure, go ahead. Thanks!

**Comment by ckingbailey** [comment]
☑️ Done

I noticed that these images are wildly different sizes. Renia Webb's is 500 kb and Kyra Mungia's is 11 kb. Should we shrink the big ones? I don't know what would be an appropriate max size. 50k?

**Comment by elinaru** [comment]
@ckingbailey If you'd like to resize the larger images, please go ahead.

**Comment by elinaru** [comment]
Hey @ckingbailey - can we get this pushed?

**Review by ckingbailey — APPROVED** [review]
it's good

**Pull request merged**
