### PR TITLE
[WIP] Added text for landing page per Elina's mockups shared on 5/1

### PR DESCRIPTION
**Pull request by mford008**
limited styling - could use help with scss, please

### CODE REVIEW

**Comment by adborden** [comment]
@mford008 maybe we can take a look at this together after demo this week?

**Comment by mford008** [comment]
@adborden Sounds good!

**Comment by adborden** [comment]
@mford008 is this PR still in progress or is it superceded by #117 ?

**Comment by mford008** [comment]
It's superceded by #117, thanks!

**Pull request closed without merging**
