### PR TITLE
make ballot-nav election date link to summary page

### LINKED ISSUE #357: Link to Election summary page from the navbar
currently there's no way to navigate to the election summary page. 

Make this link
Screen Shot 2020-03-31 at 8 38 10 PM

to the election summary page (e.g. https://www.opendisclosure.io/election/oakland/2020-11-03/)

### PR DESCRIPTION
**Pull request by ckingbailey**
This work resolves #357 

Makes election dates in ballot nav into links to election summary page for date.

### Previews
Screen Shot 2020-04-01 at 8 50 49 PM

### CODE REVIEW

**Comment by ckingbailey** [comment]
@anlawyer how's this look?

**Comment by anlawyer** [comment]
Better - it looks great! Two thoughts:

1. Could we make it so that the whole bar is clickable, and not just the date text? Just like the other list items are clickable and not only the text.
2. I think it'd look a little cleaner if the date was un-hightlighted when you click on any of the other items in the nav, so that _only_ the current page you're on is highlighted, not the date and the item. Although I could probably be convinced otherwise - what do you think?

**Comment by ckingbailey** [comment]
Ok, both make sense to me. Done and done.

Re: the second one, sorry, I thought I'd seen a mock that did it the way I had it, but I see now there is no such mock.

**Comment by anlawyer** [comment]
Beautiful, it looks awesome. One more thing - could we make it gold on hover too?

**Pull request merged**
