### PR TITLE
Add links to candidate Facebook and Instagram pages, and icons for th…

### LINKED ISSUE #406: Add Facebook and Instagram to candidate profiles
Can we add Facebook and Instagram links to candidate pages beneath the Twitter account link we have now? 

And can they be fillable from the same spreadsheet as Twitter? 
- Already added columns for Facebook and Instagram to the spreadsheet 

Screen Shot 2020-09-01 at 8 14 35 PM

### PR DESCRIPTION
**Pull request by anlawyer**
…e new social links

This work resolves #406.

Having the https://www. prefix on the links isn't the cutest, but it's the existing display for the website url. I guess we could make a little helper function to remove the string, but I haven't done that yet (or checked if we already have something like that).

Screen Shot 2020-09-30 at 9 26 34 AM

### CODE REVIEW

**Comment by anlawyer** [comment]
The build fails for this PR because `HTML-Proofer found 10 failures!` - but the logs don't say where or what the failures are... 

Any ideas?

```
bundle exec htmlproofer _site --check-html --disable-external
htmlproofer 3.9.1 | Error:  HTML-Proofer found 10 failures!
Traceback (most recent call last):
	25: from /usr/local/bundle/bin/bundle:23:in `<main>'
	24: from /usr/local/bundle/bin/bundle:23:in `load'
	23: from /usr/local/bundle/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
	22: from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
	21: from /usr/local/bundle/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
	20: from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
	19: from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/base.rb:476:in `start'
	18: from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
	17: from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor.rb:399:in `dispatch'
	16: from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
	15: from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
	14: from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli.rb:476:in `exec'
	13: from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:28:in `run'
	12: from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `kernel_load'
	11: from /usr/local/bundle/gems/bundler-2.1.4/lib/bundler/cli/exec.rb:63:in `load'
	10: from /home/circleci/project/vendor/bundle/ruby/2.7.0/bin/htmlproofer:23:in `<top (required)>'
	 9: from /home/circleci/project/vendor/bundle/ruby/2.7.0/bin/htmlproofer:23:in `load'
	 8: from /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.9.1/bin/htmlproofer:9:in `<top (required)>'
	 7: from /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary.rb:19:in `program'
	 6: from /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/program.rb:42:in `go'
	 5: from /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `execute'
	 4: from /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `each'
	 3: from /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/mercenary-0.3.6/lib/mercenary/command.rb:220:in `block in execute'
	 2: from /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.9.1/bin/htmlproofer:94:in `block (2 levels) in <top (required)>'
	 1: from /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.9.1/lib/html-proofer/runner.rb:48:in `run'
/home/circleci/project/vendor/bundle/ruby/2.7.0/gems/html-proofer-3.9.1/lib/html-proofer/runner.rb:167:in `print_failed_tests': \e[0;31;49mHTML-Proofer found 10 failures!\e[0m (RuntimeError)
make: *** [Makefile:40: test] Error 1
```

**Comment by ckingbailey** [comment]
Is it possible to run html-proofer locally in verbose mode to get more output?

**Comment by anlawyer** [comment]
@ckingbailey Finally got the checks to pass! This is ready for review/merging now.

**Review by ckingbailey — APPROVED** [review]
El Gee 2 Mi.
I agree about "https" being not so cute, but also not so urgent to fix. Is there something like string.replace() in Jekyll?

**Comment by anlawyer** [comment]
> El Gee 2 Mi.
> I agree about "https" being not so cute, but also not so urgent to fix. Is there something like string.replace() in Jekyll?

Thanks! I think I found [something that might work](https://shopify.github.io/liquid/filters/replace/) - I'll merge this for now and open another ticket for link clean up.

**Pull request merged**
